### PR TITLE
Version 0.2, with training-examples

### PR DESCRIPTION
**Pull request by dsblank**
This PR:

* adds doug@comet.ml as maintainer
* adds a training-examples folder
* one draft of an example in caret

### CODE REVIEW

**Comment by daattali** [comment]
This will not be accepted to CRAN. I'll fix later.

I'd suggest not bumping up the version until it's actually submitted to CRAN for the next "official" version. Version updates on github are considered development version and it's a convention in the R community to only bump up to 0.1.1 , 0.1.2, 0.1.3, etc so that the major/minor bumps are only used for official versions on CRAN.

**Comment by dsblank** [comment]
I'd like to go ahead and fix now. Should I change to 0.1.1 and resubmit?

**Comment by daattali** [comment]
Resubmit you mean to CRAN? No, they won't accept it. They don't like to have a submission within 2-3 weeks of a previous submission , unless it's an extremely urgent issue like some bug that's affecting tons of people. Otherwise they'll outright reject saying "please submit in a few weeks".

If you do submit this version to CRAN, they'll definitely tell you at least the following (in a very angry tone - they're known to be unpleasant and rude, so don't take it personally):

- The authors field in DESCRIPTION should be formatted as R code, which means if you have more than one you need to return a vector. So it should be `c(person(...), person(...))`. You can read or see examples about this [here](http://r-pkgs.had.co.nz/description.html#author)

- They probably won't like the "You can find a place for discussion at x". They'll say this isn't a description of the package and adds no value to the description, and should instead be moved to the README or the documentation.

- There are only certain folders that are allowed at the root directory. `train-examples` is not one of them. You can read more [here](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-structure).  Any random files that you want to include have to be placed under the `inst/` folder 

- In the example script you have two consecutive lines of code to install `caret` package but with slightly different arguments. That should be fixed, only one line is needed. 


If you plan on submitting to CRAN in the future on your own without asking for my help, you will need to invest some time into reading the documentation for how to deal with CRAN. It's a lot more cumbersome than most other languages, but the end result is that installing a package always **just works**. I suggest [R Packages](http://r-pkgs.had.co.nz/) as an easy read, and also referring to the [official CRAN guidelines](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) often (yes it's a huge document, but after submitting multiple packages I've actually had to read all of it because keep rejecting for various reasons and get angry if you don't read the manual)

**Comment by dsblank** [comment]
Ok, thanks for the feedback. We'll work on this tomorrow. Good night :)

**Comment by dsblank** [comment]
I made these changes. We can further discuss tomorrow.

**Pull request merged**
