### PR TITLE
List requirements

### PR DESCRIPTION
**Pull request by dsblank**
Need to at least mention that you need R version 3.5 or greater

### CODE REVIEW

**Comment by daattali** [comment]
The required R version is already in the DESCRIPTION file, and I set it to the latest major release 3.0.0

If you want to change the required R version, that's where it should be done.

But I don't think this should change. People don't **need** to install from source. Otherwise that's like saying that everybody who uses R must have 3.5+ which would cause a lot of problems for a lot of IT departments!

I also have the API key mentioned just below in the readme, in a dedicated section "One-time setup".

Feel free to merge if you'd like, but I don't think these changes are required

**Comment by dsblank** [comment]
Ok, but I got hung up getting starting. 

It looks like the minimum version of R needed is 3.5 because of isFALSE:

```
> exp <- create_experiment()
Error in isFALSE(x) : could not find function "isFALSE"
```
https://cran.r-project.org/bin/windows/base/old/3.5.0/NEWS.R-3.5.0.html

If true, we should mention that before diving into Installation, IMHO.

**Comment by daattali** [comment]
OK that makes sense. To be honest I tested multiple platforms and I tested on a few different recent versions of R, but I did not test very old versions of R. So the 3.0 dependency was a bad assumption to make. The DESCRIPTION can be updated to 3.5 (not in the readme though). The DESCRIPTION file lists all the package requirements in a standardized format, so that when you install a package you'll get warnings or errors if there are missing dependencies (the R version counts as a dependency).

**Comment by dsblank** [comment]
Ok, sounds good. You'll update the DESCRIPTION?

**Comment by daattali** [comment]
Done

**Pull request closed without merging**
